### PR TITLE
Loading images with relative paths

### PR DESCRIPTION
**Pull request by ircop**

### CODE REVIEW

**Comment by molteber** [comment]
Can you add tests for this, @ircop ?
If not I can go ahead and make some.

Otherwise it looks good :+1:

**Comment by ircop** [comment]
I've found some logical issue :(
How we can determine that path to image is relative path, but not absolute? Both are starting with '/', and if given image path is absolute, it will be marked as relative with current code =\

**Comment by molteber** [comment]
You can check with file_exists, to be sure its a file AND readable

**Comment by ircop** [comment]
Done, added some testing

**Pull request merged**
